"""empty message

Revision ID: 58a86503ef19
Revises: 
Create Date: 2024-11-16 04:21:02.057175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58a86503ef19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('entities_sprint_id_fkey', 'entities', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('entities_sprint_id_fkey', 'entities', 'sprints', ['sprint_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
