"""empty message

Revision ID: 64577fff29c3
Revises: b7eb46f68c83
Create Date: 2024-11-16 00:29:35.248631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64577fff29c3'
down_revision: Union[str, None] = 'b7eb46f68c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entities', 'sprint_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('entities_sprint_id_fkey', 'entities', type_='foreignkey')
    op.create_foreign_key(None, 'entities', 'sprints', ['sprint_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.create_foreign_key('entities_sprint_id_fkey', 'entities', 'sprints', ['sprint_id'], ['id'], ondelete='CASCADE')
    op.alter_column('entities', 'sprint_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
