"""empty message

Revision ID: a77fef102c83
Revises: f8b3fb67c7e0
Create Date: 2024-11-16 13:21:40.062989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77fef102c83'
down_revision: Union[str, None] = 'f8b3fb67c7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('created_by', sa.String(), nullable=True, server_default=sa.null()))
    op.add_column('entities', sa.Column('updated_by', sa.String(), nullable=True, server_default=sa.null()))
    op.add_column('entities', sa.Column('assignee', sa.String(), nullable=True, server_default=sa.null()))
    op.add_column('entities', sa.Column('owner', sa.String(), nullable=True, server_default=sa.null()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'owner')
    op.drop_column('entities', 'assignee')
    op.drop_column('entities', 'updated_by')
    op.drop_column('entities', 'created_by')
    # ### end Alembic commands ###
