"""empty message

Revision ID: d583d185554e
Revises: 64577fff29c3
Create Date: 2024-11-16 00:44:20.605994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd583d185554e'
down_revision: Union[str, None] = '64577fff29c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entities', 'parent_ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entities', 'parent_ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
